# Fill out this file to get your tests running on Github
# Documentation https://docs.github.com/en/actions/quickstart

name: Run tests
on: pull_request
jobs:
  RunOurTests: 
    run-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install modules
      run: npm install
    - name: Run tests
      run: npm test
